"""'more'

Revision ID: 10b83c799ffc
Revises: 67760973a6e9
Create Date: 2018-05-29 14:33:32.684654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10b83c799ffc'
down_revision = '67760973a6e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shape',
    sa.Column('s_id', sa.Integer(), nullable=False),
    sa.Column('a_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['a_id'], ['annotation.a_id'], ),
    sa.PrimaryKeyConstraint('s_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shape')
    # ### end Alembic commands ###
