"""added note column and handling for shapes

Revision ID: 2b31c874c521
Revises: 69ed4b86cffb
Create Date: 2019-01-23 22:16:04.131791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b31c874c521'
down_revision = '69ed4b86cffb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shape', sa.Column('note', sa.String(length=128)))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shape', 'note')
    # ### end Alembic commands ###
