"""added active column to galaxy table

Revision ID: 466699916d2f
Revises: fd96049a5c3b
Create Date: 2019-04-05 19:25:52.033558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '466699916d2f'
down_revision = 'fd96049a5c3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('galaxy', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('galaxy', 'active')
    # ### end Alembic commands ###
