"""'postgres'

Revision ID: 6592c394333b
Revises: 87e4a9486b70
Create Date: 2018-10-01 16:57:34.868451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6592c394333b'
down_revision = '87e4a9486b70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('galaxy',
    sa.Column('g_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('survey', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('g_id')
    )
    with op.batch_alter_table('galaxy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_galaxy_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_galaxy_survey'), ['survey'], unique=False)

    op.create_table('annotation',
    sa.Column('a_id', sa.Integer(), nullable=False),
    sa.Column('g_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['g_id'], ['galaxy.g_id'], ),
    sa.PrimaryKeyConstraint('a_id')
    )
    with op.batch_alter_table('annotation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_annotation_timestamp'), ['timestamp'], unique=False)

    op.create_table('shape',
    sa.Column('s_id', sa.Integer(), nullable=False),
    sa.Column('a_id', sa.Integer(), nullable=True),
    sa.Column('shape', sa.String(length=64), nullable=False),
    sa.Column('x0', sa.Float(), nullable=False),
    sa.Column('y0', sa.Float(), nullable=False),
    sa.Column('sigma', sa.Float(), nullable=False),
    sa.Column('w', sa.Float(), nullable=True),
    sa.Column('h', sa.Float(), nullable=True),
    sa.Column('r', sa.Float(), nullable=True),
    sa.Column('x1', sa.Float(), nullable=True),
    sa.Column('x2', sa.Float(), nullable=True),
    sa.Column('x3', sa.Float(), nullable=True),
    sa.Column('y1', sa.Float(), nullable=True),
    sa.Column('y2', sa.Float(), nullable=True),
    sa.Column('y3', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['a_id'], ['annotation.a_id'], ),
    sa.PrimaryKeyConstraint('s_id')
    )
    with op.batch_alter_table('shape', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shape_shape'), ['shape'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shape', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shape_shape'))

    op.drop_table('shape')
    with op.batch_alter_table('annotation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_annotation_timestamp'))

    op.drop_table('annotation')
    with op.batch_alter_table('galaxy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_galaxy_survey'))
        batch_op.drop_index(batch_op.f('ix_galaxy_name'))

    op.drop_table('galaxy')
    # ### end Alembic commands ###
