"""shapes json

Revision ID: 67760973a6e9
Revises: ee2e75296f40
Create Date: 2018-05-28 03:23:33.753019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67760973a6e9'
down_revision = 'ee2e75296f40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annotation', schema=None) as batch_op:
        batch_op.drop_column('x0')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annotation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('x0', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
