"""shape table

Revision ID: 87e4a9486b70
Revises: ee2e75296f40
Create Date: 2018-05-30 14:39:25.106117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87e4a9486b70'
down_revision = 'ee2e75296f40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annotation', schema=None) as batch_op:
        batch_op.drop_column('x0')

    with op.batch_alter_table('galaxy', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('galaxy', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    with op.batch_alter_table('annotation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('x0', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
