"""points columns on shape table

Revision ID: 8e1269bc8468
Revises: 26b2853a6278
Create Date: 2018-10-02 13:41:24.818098

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8e1269bc8468'
down_revision = '26b2853a6278'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shape', schema=None) as batch_op:
        batch_op.add_column(sa.Column('x_points', postgresql.ARRAY(sa.Float()), nullable=True))
        batch_op.add_column(sa.Column('y_points', postgresql.ARRAY(sa.Float()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shape', schema=None) as batch_op:
        batch_op.drop_column('y_points')
        batch_op.drop_column('x_points')

    # ### end Alembic commands ###
