"""annotation table name change

Revision ID: 9c5ecda15cc1
Revises: 9d391c25ab6d
Create Date: 2018-03-05 23:40:51.078727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c5ecda15cc1'
down_revision = '9d391c25ab6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotation',
    sa.Column('a_id', sa.Integer(), nullable=False),
    sa.Column('g_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['g_id'], ['galaxy.g_id'], ),
    sa.PrimaryKeyConstraint('a_id')
    )
    op.create_index(op.f('ix_annotation_timestamp'), 'annotation', ['timestamp'], unique=False)
    op.drop_index('ix_annotations_timestamp', table_name='annotations')
    op.drop_table('annotations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotations',
    sa.Column('a_id', sa.INTEGER(), nullable=False),
    sa.Column('g_id', sa.INTEGER(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['g_id'], ['galaxy.g_id'], ),
    sa.PrimaryKeyConstraint('a_id')
    )
    op.create_index('ix_annotations_timestamp', 'annotations', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_annotation_timestamp'), table_name='annotation')
    op.drop_table('annotation')
    # ### end Alembic commands ###
