"""added columns for rect/ellipse individual wcs

Revision ID: dccd9ceeb2a8
Revises: 466699916d2f
Create Date: 2021-02-24 16:47:28.653101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dccd9ceeb2a8'
down_revision = '466699916d2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('galaxy', 'morph_type')
    op.add_column('shape', sa.Column('dec_bl', sa.REAL(), nullable=True))
    op.add_column('shape', sa.Column('dec_br', sa.REAL(), nullable=True))
    op.add_column('shape', sa.Column('dec_tl', sa.REAL(), nullable=True))
    op.add_column('shape', sa.Column('dec_tr', sa.REAL(), nullable=True))
    op.add_column('shape', sa.Column('ra_bl', sa.REAL(), nullable=True))
    op.add_column('shape', sa.Column('ra_br', sa.REAL(), nullable=True))
    op.add_column('shape', sa.Column('ra_tl', sa.REAL(), nullable=True))
    op.add_column('shape', sa.Column('ra_tr', sa.REAL(), nullable=True))
    # op.drop_column('user', 'weight')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('user', sa.Column('weight', sa.REAL(), autoincrement=False, nullable=True))
    op.drop_column('shape', 'ra_tr')
    op.drop_column('shape', 'ra_tl')
    op.drop_column('shape', 'ra_br')
    op.drop_column('shape', 'ra_bl')
    op.drop_column('shape', 'dec_tr')
    op.drop_column('shape', 'dec_tl')
    op.drop_column('shape', 'dec_br')
    op.drop_column('shape', 'dec_bl')
    # op.add_column('galaxy', sa.Column('morph_type', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
