"""empty message

Revision ID: e607f5443a8d
Revises: 
Create Date: 2018-10-03 14:59:46.392881

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e607f5443a8d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('galaxy',
    sa.Column('g_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('survey', sa.String(length=64), nullable=True),
    sa.Column('ra', sa.REAL(), nullable=True),
    sa.Column('dec', sa.REAL(), nullable=True),
    sa.PrimaryKeyConstraint('g_id')
    )
    op.create_index(op.f('ix_galaxy_dec'), 'galaxy', ['dec'], unique=False)
    op.create_index(op.f('ix_galaxy_name'), 'galaxy', ['name'], unique=True)
    op.create_index(op.f('ix_galaxy_ra'), 'galaxy', ['ra'], unique=False)
    op.create_index(op.f('ix_galaxy_survey'), 'galaxy', ['survey'], unique=False)
    op.create_table('annotation',
    sa.Column('a_id', sa.Integer(), nullable=False),
    sa.Column('g_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['g_id'], ['galaxy.g_id'], ),
    sa.PrimaryKeyConstraint('a_id')
    )
    op.create_index(op.f('ix_annotation_timestamp'), 'annotation', ['timestamp'], unique=False)
    op.create_table('shape',
    sa.Column('s_id', sa.Integer(), nullable=False),
    sa.Column('a_id', sa.Integer(), nullable=True),
    sa.Column('shape', sa.String(length=64), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('feature', sa.String(length=32), nullable=False),
    sa.Column('x0', sa.REAL(), nullable=False),
    sa.Column('y0', sa.REAL(), nullable=False),
    sa.Column('ra_xy', sa.REAL(), nullable=True),
    sa.Column('dec_xy', sa.REAL(), nullable=True),
    sa.Column('theta', sa.REAL(), nullable=True),
    sa.Column('xw', sa.REAL(), nullable=True),
    sa.Column('yh', sa.REAL(), nullable=True),
    sa.Column('ra_wh', sa.REAL(), nullable=True),
    sa.Column('dec_wh', sa.REAL(), nullable=True),
    sa.Column('r', sa.REAL(), nullable=True),
    sa.Column('x1', sa.REAL(), nullable=True),
    sa.Column('x2', sa.REAL(), nullable=True),
    sa.Column('x3', sa.REAL(), nullable=True),
    sa.Column('y1', sa.REAL(), nullable=True),
    sa.Column('y2', sa.REAL(), nullable=True),
    sa.Column('y3', sa.REAL(), nullable=True),
    sa.Column('ra1', sa.REAL(), nullable=True),
    sa.Column('ra2', sa.REAL(), nullable=True),
    sa.Column('ra3', sa.REAL(), nullable=True),
    sa.Column('dec1', sa.REAL(), nullable=True),
    sa.Column('dec2', sa.REAL(), nullable=True),
    sa.Column('dec3', sa.REAL(), nullable=True),
    sa.Column('x_points', postgresql.ARRAY(sa.REAL()), nullable=True),
    sa.Column('y_points', postgresql.ARRAY(sa.REAL()), nullable=True),
    sa.Column('ra_points', postgresql.ARRAY(sa.REAL()), nullable=True),
    sa.Column('dec_points', postgresql.ARRAY(sa.REAL()), nullable=True),
    sa.ForeignKeyConstraint(['a_id'], ['annotation.a_id'], ),
    sa.PrimaryKeyConstraint('s_id')
    )
    op.create_index(op.f('ix_shape_shape'), 'shape', ['shape'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shape_shape'), table_name='shape')
    op.drop_table('shape')
    op.drop_index(op.f('ix_annotation_timestamp'), table_name='annotation')
    op.drop_table('annotation')
    op.drop_index(op.f('ix_galaxy_survey'), table_name='galaxy')
    op.drop_index(op.f('ix_galaxy_ra'), table_name='galaxy')
    op.drop_index(op.f('ix_galaxy_name'), table_name='galaxy')
    op.drop_index(op.f('ix_galaxy_dec'), table_name='galaxy')
    op.drop_table('galaxy')
    # ### end Alembic commands ###
