"""added test coord

Revision ID: ee2e75296f40
Revises: 9c5ecda15cc1
Create Date: 2018-03-06 18:07:49.822450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee2e75296f40'
down_revision = '9c5ecda15cc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation', sa.Column('x0', sa.Float(precision=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('annotation', 'x0')
    # ### end Alembic commands ###
