"""new columns for galaxy

Revision ID: fd96049a5c3b
Revises: 2b31c874c521
Create Date: 2019-04-05 15:53:55.492769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd96049a5c3b'
down_revision = '2b31c874c521'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('galaxy', sa.Column('bands', sa.String(length=64), nullable=True))
    op.add_column('galaxy', sa.Column('fov', sa.REAL(), nullable=True))
    op.create_index(op.f('ix_galaxy_bands'), 'galaxy', ['bands'], unique=False)
    op.create_index(op.f('ix_galaxy_fov'), 'galaxy', ['fov'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_galaxy_fov'), table_name='galaxy')
    op.drop_index(op.f('ix_galaxy_bands'), table_name='galaxy')
    op.drop_column('galaxy', 'fov')
    op.drop_column('galaxy', 'bands')
    # ### end Alembic commands ###
