"""changed types to psql real

Revision ID: fd9c279e8fa9
Revises: 8e1269bc8468
Create Date: 2018-10-02 22:00:39.144170

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fd9c279e8fa9'
down_revision = '8e1269bc8468'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shape', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dec1', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('dec2', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('dec3', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('dec_points', postgresql.ARRAY(sa.Float()), nullable=True))
        batch_op.add_column(sa.Column('dec_wh', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('dec_xy', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('feature', sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column('number', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('ra1', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ra2', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ra3', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ra_points', postgresql.ARRAY(sa.Float()), nullable=True))
        batch_op.add_column(sa.Column('ra_wh', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ra_xy', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('theta', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('xw', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('yh', sa.Float(), nullable=True))
        batch_op.drop_column('h')
        batch_op.drop_column('sigma')
        batch_op.drop_column('w')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shape', schema=None) as batch_op:
        batch_op.add_column(sa.Column('w', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sigma', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('h', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('yh')
        batch_op.drop_column('xw')
        batch_op.drop_column('theta')
        batch_op.drop_column('ra_xy')
        batch_op.drop_column('ra_wh')
        batch_op.drop_column('ra_points')
        batch_op.drop_column('ra3')
        batch_op.drop_column('ra2')
        batch_op.drop_column('ra1')
        batch_op.drop_column('number')
        batch_op.drop_column('feature')
        batch_op.drop_column('dec_xy')
        batch_op.drop_column('dec_wh')
        batch_op.drop_column('dec_points')
        batch_op.drop_column('dec3')
        batch_op.drop_column('dec2')
        batch_op.drop_column('dec1')

    # ### end Alembic commands ###
